<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-12-29T00:35:39 PST" name="Default suite" finished-at="2019-12-29T00:35:40 PST" duration-ms="1115">
    <groups>
    </groups>
    <test started-at="2019-12-29T00:35:39 PST" name="Default test" finished-at="2019-12-29T00:35:40 PST" duration-ms="1115">
      <class name="com.restapi.test.TC101_POSTEmp_Details">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.restapi.test.TC101_POSTEmp_Details@35047d03]" started-at="2019-12-29T00:35:39 PST" name="setup" finished-at="2019-12-29T00:35:39 PST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="PostEmpDetails()[pri:0, instance:com.restapi.test.TC101_POSTEmp_Details@35047d03]" started-at="2019-12-29T00:35:39 PST" name="PostEmpDetails" finished-at="2019-12-29T00:35:40 PST" duration-ms="1060" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PostEmpDetails -->
        <test-method signature="validateContentType()[pri:0, instance:com.restapi.test.TC101_POSTEmp_Details@35047d03]" started-at="2019-12-29T00:35:40 PST" name="validateContentType" finished-at="2019-12-29T00:35:40 PST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateContentType -->
        <test-method signature="validateResponseBody()[pri:0, instance:com.restapi.test.TC101_POSTEmp_Details@35047d03]" started-at="2019-12-29T00:35:40 PST" name="validateResponseBody" finished-at="2019-12-29T00:35:40 PST" duration-ms="11" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at com.restapi.test.TC101_POSTEmp_Details.validateResponseBody(TC101_POSTEmp_Details.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateResponseBody -->
        <test-method signature="validateStatusCode()[pri:0, instance:com.restapi.test.TC101_POSTEmp_Details@35047d03]" started-at="2019-12-29T00:35:40 PST" name="validateStatusCode" finished-at="2019-12-29T00:35:40 PST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateStatusCode -->
      </class> <!-- com.restapi.test.TC101_POSTEmp_Details -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
